name: Send Email
on:
  push:
    branches:
      - main
jobs:
  email:
    runs-on: ubuntu-latest
    steps:
    - name: Send Email
      uses: actions/email@v2
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: 'GitHub Action Email'
        to: 'recipient@example.com'
        from: 'sender@example.com'
        body: 'This is a test email sent from a GitHub Action.'
