jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Choose a file
        uses: actions/github-script@v4
        with:
          script: |
            const { data: files } = await octokit.rest.repos.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: '.'
            });
            const fileNames = files.map(file => file.name);
            return {
              inputs: {
                fileName: {
                  description: 'Select a file to use',
                  required: true,
                  type: 'select',
                  options: fileNames
                }
              }
            };
          ad: true
      - name: Use the chosen file
        run: |
          echo "The chosen file is ${{ github.event.inputs.fileName }}"
