name: My user trigger

on:
  workflow_dispatch:

jobs:
  run_batch_file:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run batch file
        run: .\Box.bat
