name: User trigger
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Building..."
      - name: Test
        run: echo "Testing..."

  gui:
    runs-on: windows-latest
    needs: []
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run GUI
        run: |
          $yaml = Get-Content -Path .\Manual_trigger.yml -Raw
          $workflow = ConvertFrom-Yaml -InputObject $yaml
          $jobNames = $workflow.jobs.psobject.Properties.Name
          $selectedJob = $jobNames | Out-GridView -Title "Select a job to run" -PassThru
          Write-Host "You selected job $selectedJob"
