name: Select and Run Batch File

on:
  workflow_dispatch:
    inputs:
      batchfile:
        description: 'Select a batch file to run'
        required: true
        type: file
        # Optional: limit the file types that can be selected
        # contentTypes:
        #   - application/x-bat

jobs:
  run-batch-file:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run batch file
        shell: cmd
        run: '${{ env.BATCHFILE }}'
        env:
          BATCHFILE: ${{ github.event.inputs.batchfile.path }}
