name: My user trigger

on:
  workflow_dispatch:
    inputs:
      file:
        description: 'File to run'
        required: true
        default: '.\Box.bat'
        
jobs:
  my_job:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run file
        run:  ${{ github.workspace }}/${{ inputs.file }}
        # The input parameter 'file' is used to specify the file to run



