name: Select and Run Batch File

on:
  workflow_dispatch:
    inputs:
      batchfile:
        description: 'Select a batch file to run'
        required: true
        type: file
        # Optional: limit the file types that can be selected
        # contentTypes:
        #   - application/x-bat

jobs:
  run-batch-file:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display batch file
        run: cat ${{ github.event.inputs.batchfile.name }}

      - name: Run batch file
        working-directory: .
        run: ${{ github.event.inputs.batchfile.name }}
