name: My user trigger

on:
  workflow_dispatch:
    inputs:
      file:
        description: 'File to run'
        required: true

jobs:
  run-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run file
        run: |
          file_to_run=$INPUT_FILE
          # Run the file using the appropriate command
          echo "Running $file_to_run"
