name: multiselection


on:
  workflow_dispatch:
    inputs:
      option1:
        description: 'Option 1'
        required: true
        default: 'a'
      option2:
        description: 'Option 2'
        required: true
        default: 'x'
      matrix:
        description: 'Matrix of options'
        required: true
        options:
            - 'true'
            - 'false'
            - 'maybe'
jobs:
  build:
    runs-on: windows-latest



    steps:
    - name: Display options
      run: |
        echo "option1: ${{ matrix.option1 }}"
        echo "option2: ${{ matrix.option2 }}"
        echo "option3: ${{ matrix.option3 }}"
