name: Multiselection

on:
  workflow_dispatch:
    inputs:
      component1:
        description: 'CTM'
        required: true
        default: false
        type: boolean
 
      component1unit1:
        description: 'unit1'
        required: true
        default: false
        type: boolean
        
      component1unit2:
        description: 'unit2'
        required: true
        default: false
        type: boolean
        
      component1unit3:
        description: 'unit3'
        required: true
        default: false
        type: boolean
        
      component2:
        description: 'HLC'
        required: true
        default: false
        type: boolean
 
      component2unit1:
        description: 'unit1'
        required: true
        default: false
        type: boolean
        
      component2unit2:
        description: 'unit2'
        required: true
        default: false
        type: boolean
        
      component2unit3:
        description: 'unit3'
        required: true
        default: false
        type: boolean

     

        
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run CMS UNIT1
        if: ${{ github.event.inputs.component1 == 'true'}} &&  ${{ github.event.inputs.component1unit1 == 'true'}}
        run: .\CMS\unit1\file1.bat
      - name: Run CMS UNIT2
        if: ${{ github.event.inputs.component1 == 'true'}} &&  ${{ github.event.inputs.component1unit2 == 'true' }}
        run: .\CMS\unit2\file1.bat
      - name: Run CMS UNIT3
        if: ${{ github.event.inputs.component1 == 'true'}} &&  ${{ github.event.inputs.component1unit3 == 'true'}}
        run: .\CMS\unit3\file1.bat     
        
      - name: Run CTM UNIT1
        if: ${{ github.event.inputs.component2 == 'true'}} &&  ${{ github.event.inputs.component2unit1 == 'true'}}
        run: .\CMS\unit1\file1.bat
      - name: Run CTM UNIT2
        if: ${{ github.event.inputs.component2 == 'true'}} &&  ${{ github.event.inputs.component2unit2 == 'true'}}
        run: .\CMS\unit2\file1.bat
      - name: Run CTM UNIT3
        if: ${{ github.event.inputs.component2 == 'true'}} &&  ${{ github.event.inputs.component2unit3 == 'true'}}
        run: .\CMS\unit3\file1.bat  
        
  

        
        
        
        
        
        
