name: multiselection

on:
  repository_dispatch:
    types:
      - test
 
jobs:
  example_matrix:
    runs-on: windows-latest
    strategy:
      matrix:
        fruit: [apple, pear]
        animal: [cat, dog]
        include:
          - color: green
          - color: pink
            animal: cat
          - fruit: apple
            shape: circle
          - fruit: banana
          - fruit: banana
            animal: cat





