name: multiselection


on:
  workflow_dispatch:
    inputs:
      units:
        type: choice
        description: 'Select Unit'
        required: true
        default: 'CMS'
        options: ['CMS', 'CTM', 'HLC']

jobs:
  build-and-test:
    runs-on: ${{ matrix.units }}
    strategy:
      matrix:
        units: ${{ fromJson(inputs.units) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # rest of the job steps





