name: multiselection


on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Select options
        run: |
          echo "Choose options:"
          echo "1. Option 1"
          echo "2. Option 2"
          echo "3. Option 3"
          read -p "Enter comma-separated numbers: " options
          echo "Selected options: $options"
        env:
          options: ${{ github.event.inputs.options }}
        shell: bash
        if: github.event_name == 'workflow_dispatch'

      - name: Build
        run: echo "Building..."


