name: multiselection

on: [push]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        unit: [unit1, unit2, unit3, unit4]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run unit tests
        run: |
          if ( "${{ matrix.unit }}" == "unit1" ); then
            echo "Running unit1 tests"
          fi
          if ( "${{ matrix.unit }}" == "unit2" ); then
            echo "Running unit2 tests"
          fi
          if ( "${{ matrix.unit }}" == "unit3" ); then
            echo "Running unit3 tests"
          fi
          if ( "${{ matrix.unit }}" == "unit4" ); then
            echo "Running unit4 tests"
          fi






