name: Multiselection

on:
  workflow_dispatch:
    inputs:
      component1:
        type: choice
        description: 'Select the component to run'
        required: true
        default: ''
        options:
          - CTM
          - CMS
          - HLC
      component2:
        type: choice
        description: 'Select the component to run'
        required: true
        default: ''
        options:
          - CTM
          - CMS
          - HLC
      component3:
        type: choice
        description: 'Select the component to run'
        required: true
        default: ''
        options:
          - CTM
          - CMS
          - HLC
      unit:
        type: choice
        description: 'Select the unit to run'
        required: true
        default: ''
        options:
          - unit1
          - unit2
          - unit3
      file_name:
        description: 'Select a file'
        required: true
        default: ''

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run selected component1
        run:  ${{ inputs.component1 }}/${{ inputs.unit }}/${{ inputs.file_name }}
      - name: Run selected component2
        run:  ${{ inputs.component2 }}/${{ inputs.unit }}/${{ inputs.file_name }}
      - name: Run selected component3
        run:  ${{ inputs.component3 }}/${{ inputs.unit }}/${{ inputs.file_name }}
        
        
        
        
        
        
