name: multiselection

on: [push]
jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        unit: [unit1, unit2, unit3]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run unit tests
      run: |
        cd ${{ matrix.unit }}
        dotnet test
