name: multiselection


on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Operating system'
        required: true
        default: 'ubuntu-latest'
        options: ['ubuntu-latest', 'macos-latest', 'windows-latest']

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ${{ fromJson(inputs.os) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # rest of the job steps





