name: Multiselection

on:
  workflow_dispatch:
    inputs:
      component1:
        type: choice
        description: 'Select the component1 to run'
        required: true
        default: ''
        options:
          - CTM
          - CMS
          - HLC
      component1unit:
        type: choice
        description: 'Select the unit of component1 to run'
        required: true
        default: ''
        options:
          - unit1
          - unit2
          - unit3
      Component1file_name:
        description: 'Select a file of component1'
        required: true
        default: ''
        
      component2:
        type: choice
        description: 'Select the component2 to run'
        required: true
        default: ''
        options:
          - CTM
          - CMS
          - HLC
      component2unit:
        type: choice
        description: 'Select the unit of component2 to run'
        required: true
        default: ''
        options:
          - unit1
          - unit2
          - unit3 
      Component2file_name:
        description: 'Select a file of component2'
        required: true
        default: ''
        
      component3:
        type: choice
        description: 'Select the component3 to run'
        required: true
        default: ''
        options:
          - CTM
          - CMS
          - HLC
      component3unit:
        type: choice
        description: 'Select the unit of component3 to run'
        required: true
        default: ''
        options:
          - unit1
          - unit2
          - unit3
      Component3file_name:
        description: 'Select a file of component 3'
        required: true
        default: ''

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run selected component1
        run:  ${{ inputs.component1 }}/${{ inputs.component1unit }}/${{ inputs.Component1file_name }}
      - name: Run selected component2
        run:  ${{ inputs.component2 }}/${{ inputs.component2unit }}/${{ inputs.Component2file_name }}
      - name: Run selected component3
        run:  ${{ inputs.component3 }}/${{ inputs.component3unit }}/${{ inputs.Component3file_name }}
        
        
        
        
        
        
