name: multiselection

on:
  workflow_dispatch:
    inputs:
      choice:
        description: 'Choose an option'
        required: true
        default: 'Option 1'
        options: |
          Option 1
          Option 2
          Option 3

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Run a script
        run: |
          choice=${{ github.event.inputs.choice }}
          echo "Selected choice: $choice"






