name: multiselection
on:
  workflow_dispatch:
    inputs:
      num_units:
        description: 'Number of units to run the workflow on'
        required: true


jobs:
  my_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        units: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run units
        run: |
          for i in $(seq 1 ${{ matrix.units }}); do
            echo "Running unit $i"
            # run the command for the current unit
          done

