name: multiselection

on: [push]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        unit: [unit1, unit2, unit3, unit4]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run unit tests
        run: |
          if ( "${{ matrix.unit }}" == "unit1" );
            echo "Running unit1 tests"
        
          if ( "${{ matrix.unit }}" == "unit2" ); 
            echo "Running unit2 tests"
        
          if ( "${{ matrix.unit }}" == "unit3" );
            echo "Running unit3 tests"
        
          if ( "${{ matrix.unit }}" == "unit4" ); 
            echo "Running unit4 tests"
        






