name: Run Batch File Every Minute

on:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  run-batch-file:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run batch file
      run: Box.bat
