name: Run batch file

on: [push]

jobs:
  run_batch:
    runs-on: windows-latest

    steps:
    - name: Run batch file
      env:
        BATCH_FILE: C:\PRATHIBHA\yaml\Box.bat
      run: |
        cmd /c "$env:BATCH_FILE"
    - name: Print BATCH_FILE
      run: |
        echo "$env:BATCH_FILE"
