name: Run Batch Script

on: [push]

jobs:
  run-batch-script:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up environment
      run: |
        cd c:\PRATHIBHA\yaml

    - name: Run batch script
      run: |
        Box.bat

    - name: Echo result
      run: |
        echo The script has run successfully.
