name: Batch File Runner

on:[push]

jobs:
  run-batch-file:
    runs-on: windows-latest

    steps:
    - name: Run Batch File
      run: echo %cd%
      shell: cmd

    - name: Print Local Machine Path
      run: echo %cd%
      shell: cmd
