name: Run_repo_contents


on:
  workflow_dispatch:

jobs:
  list_files:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: List files
        shell: pwsh
        run: |
          $files = Get-ChildItem -Path . -Recurse | Where-Object { !$_.PSIsContainer }
          Write-Host "Files in repository:"
          foreach ($file in $files) {
            Write-Host $file.FullName
          }
