name: Run_repo_contents

on:
  workflow_dispatch:
    inputs:
      units:
        description: 'Select the units'
        required: true
        default: 'unit1,unit2,unit3'

jobs:
  example_job:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run unit tests
        run: |
          units=${{ github.event.inputs.units }}
            if : (${{units}} == "unit1")
            run: ".\CMS\unit1\file1.bat

            if: (${{units}} == "unit2")
            run: ".\CMS\unit2\file1.bat
 
            if: (${{units}} == "unit3")
              run: ".\CMS\unit3\file1.bat

