name: Run_repo_contents

on:
  workflow_dispatch:
    inputs:
      units:
        description: 'Select the units'
        required: true
        default: '.\CMS\unit1,.\CMS\unit2,.\CMS\unit3'

jobs:
  example_job:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run unit tests
        run: |
          units=${{ github.event.inputs.units }}
          for unit in $(echo $units | sed "s/,/ /g")
          do
            echo "Running tests for $unit"
            run: file1.bat
          done

