name: Run_repo_contents

on:
  workflow_dispatch:
  
jobs:
  list-files:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: List files
        run: |
          cd .github/workflows
          dir ./
