name: Run_repo_contents

on: [push]

jobs:
  my_job:
    strategy:
      matrix:
        unit: [unit1, unit2]
    runs-on: windows-latest
    steps:
    - name: Run only unit1
      if: matrix.unit == 'unit1'
      run: |
        echo "This is unit1"
