name: Run_repo_contents

on:
  workflow_dispatch:
    inputs:
      component:
        description: 'Select the component to run'
        required: true
        default: ''
        options:
          - CTM
          - CMS
          - HLC
      unit:
        description: 'Select the unit to run'
        required: true
        default: ''
        options:
          - unit1
          - unit2
          - unit3
      file_name:
        description: 'Select a file'
        required: true
        default: ''
        type: string
        options: |
          ${{ join(', ', (ls() | select(match('^(${{ inputs.component }}/${{ inputs.unit }}).*\\.bat$')) | map('basename') | list)) }}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run selected unit
        run:  ${{ inputs.component }}/${{ inputs.unit }}/${{ inputs.file_name }}
        
        
