name: Run_repo_contents

on:
  workflow_dispatch:
    inputs:
      my_matrix_param:
        description: 'A matrix parameter'
        required: true
        default: 'foo,bar'

jobs:
  my_job:
    runs-on: windows-latest
    strategy:
      matrix:
        my_matrix_param: ${{ matrix.my_matrix_param }}

    steps:
      - name: Run my command
        run: echo "My matrix parameter is ${{ matrix.my_matrix_param }}"
