name: Run_repo_contents

on: [push]

jobs:
  my_job:
    strategy:
      matrix:
        option1: [value1, value2, value3]
        option2: [value4, value5, value6]
        include:
          - option1: value2
    runs-on: ubuntu-latest
    steps:
      - name: My step
        run: echo "Hello, World!"

