name: Run_repo_contents


on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to use'
        required: true
        default: 'main'
      label:
        description: 'The label to use'
        required: true
        default: 'CTM'

jobs:
  my_job:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run file
        run:  ${{ github.workspace }}/${{ inputs.branch.label }}
        # The input parameter 'choice' is used to specify the file to run
