name: Run_repo_contents

on:
  workflow_dispatch:
    inputs:
      units:
        description: 'Select the units'
        required: true
        default: 'unit1,unit2,unit3'

jobs:
  example_job:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run unit tests
        run: |
          units=${{ github.event.inputs.units }}
          for unit in $(echo $units | sed "s/,/ /g") do
            echo "Running tests for $unit"
            run: ".\CMS\"${{units}}\file1.bat
          done

