name: Run_repo_contents

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Make a choice
        options:
        - .\unit1
        - .\unit2
        - .\unit3
        

jobs:
  my-job:
    strategy:
      matrix:
        unit: ${{ matrix.choice }}

    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add steps for each unit
      - name: Build unit 1
        if: matrix.unit == 'unit1'
        run: .\CMS\unit1\file1.bat

      - name: Build unit 2
        if: matrix.unit == 'unit2'
        run: .\CMS\unit2\file1.bat

      - name: Build unit 3
        if: matrix.unit == 'unit3'
        run: .\CMS\unit3\file1.bat

