name: Run_repo_contents


on:
  workflow_dispatch:
    inputs:
      unit1:
        description: 'Select unit1 CMS only'
        required: false
        default: ''
      unit2:
        description: 'Select unit2 HLC only'
        required: false
        default: ''
      unit3:
        description: 'Select unit3 CTM only'
        required: false
        default: ''

jobs:
  unit1:
    runs-on: windows-latest
    if: ${{ github.event.inputs.unit1 == 'CMS' }}
    steps:
    - uses: actions/checkout@v1
    - name: execute CMS
      run: .\CMS\unit1\file1.bat


  unit2:
    runs-on: windows-latest
    if: ${{ github.event.inputs.unit2 == 'HLC' }}
    steps:
    - uses: actions/checkout@v1
    - name: execute HLC
      run: .\HLC\unit1\file1.bat
      
  unit3:
    runs-on: windows-latest
    if: ${{ github.event.inputs.unit3 == 'CTM' }}
    steps:
    - uses: actions/checkout@v1
    - name: execute CTM
      run: .\CTM\unit1\file1.bat

