name: Run_repo_contents

on:
  workflow_dispatch:
    inputs:
      selection:
        description: 'Select an option'
        required: true
        default: 'option1'
jobs:
  my_job:
    strategy:
      matrix:
        option: [ ${{ github.event.inputs.selection }} ]
    runs-on: windows-latest
    steps:
      - name: Step 1
        run: echo "Running option ${{ matrix.option }}"

