name: Run_repo_contents


on:
  workflow_dispatch:
    inputs:
      folder_path:
        description: 'The path of the folder to trigger the workflow'
        required: true
        default: ''

jobs:
  display_folder:
    runs-on: Windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Display folder
        run: ls ${{ github.workspace }}/${{ github.event.inputs.folder_path }}
