name: Run_repo_contents


on:
  workflow_dispatch:
    inputs:
      multiunit:
        description: 'Select multiunit'
        required: true
        default: 'unit1'

jobs:
  unit1:
    runs-on: windows-latest
    if: ${{ github.event.inputs.multiunit == 'unit1' }}
    steps:
      - name: Step 1
        run: .\Box.bat


  unit2:
    runs-on: windows-latest
    if: ${{ github.event.inputs.multiunit == 'unit2' }}
    steps:
      - name: Step 1
        run: .\allclr.bat

