name: Run_repo_contents

on:
  workflow_dispatch:
    inputs:
      my_matrix_param1:
        description: 'A matrix parameter'
        required: true
        default: 'unit2'

jobs:
  my_job:
    runs-on: windows-latest
    strategy:
      matrix:
        my_matrix_param: ${{ matrix.my_matrix_param1 }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add steps for each unit
      - name: Build unit 1
        if: matrix.unit == 'unit1'
        run: .\CMS\unit1\file1.bat

      - name: Build unit 2
        if: matrix.unit == 'unit2'
        run: .\CMS\unit2\file1.bat

      - name: Build unit 3
        if: matrix.unit == 'unit3'
        run: .\CMS\unit3\file1.bat

