name: Run_repo_contents


on:
  workflow_dispatch:
    inputs:
      directory:
        description: 'The directory to display'
        required: true

jobs:
  display-directory-tree:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Display directory tree
        run: |
          cd ${{ github.workspace }}/${{ github.event.inputs.directory }}
          tree
