name: Run_repo_contents

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to run the file from'
        required: true
      file:
        description: 'The file to run'
        required: true

jobs:
  run-file:
    runs-on: windows-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch }}
      - name: Execute file
        run: |
          # Replace this with the command or script to run your file
          ${{ github.workspace }}/${{ inputs.file }}

