name: Run_repo_contents


on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to use'
        required: true
        default: 'main'
      label:
        description: 'The label to use'
        required: true
        default: 'CTM'

jobs:
  my-job:
    runs-on: windows-latest
    if: ${{ github.ref == 'refs/heads/' + inputs.branch && (!inputs.label || github.event.inputs.label == inputs.label) }}
    steps:
      - name: My Step
        run: echo "Hello, world!"
