name: selectmultipleunit

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        unit: [unit1, unit2, unit3]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run:  tests/unit/$unit
