name: selectmultipleunit

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        selected_matrix: [unit1, unit2, unit3]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        if: matrix.selected_matrix == unit1
        run: echo "selected unit1"
  
