name: selectmultipleunit

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        Component: [component1, component2]
        Unit: [unit1, unit2]
        file: [file1.bat,file2.bat]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: |
          if ( "${{ matrix.selected }}" == "true" ); then
            echo "running job1"
          else
             echo "running job2"
          fi

  
