name: trial


on:
  workflow_dispatch:
    inputs:
      parameter1:
        description: 'Enter a value for parameter1'
        required: true
      parameter2:
        description: 'Enter a value for parameter2'
        required: true

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "This is step 1"
      - name: Step 2
        run: echo "This is step 2"
        if: github.ref == 'refs/heads/main'
        env:
          PARAMETER_3: ${{ github.event.inputs.parameter1 }}
      - name: Step 3
        run: echo "This is step 3"
        if: github.ref == 'refs/heads/develop'
        env:
          PARAMETER_4: ${{ github.event.inputs.parameter2 }}




