name: trial

on: [push]

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
    - name: My Action
      uses: actions/checkout@v2
      with:
        input1: "value1"
        input2: "value2"
      run: |
        echo "Input 1 is ${{ inputs.input1 }}"
        echo "Input 2 is ${{ inputs.input2 }}"

