name: trial


on:
  workflow_dispatch:
    branches:
      - main
      - developer

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Do something
        run: echo "Hello, world!"
      - name: Use parameter
        if: github.ref == 'refs/heads/developer'
        run: echo "This is a parameter for the developer branch."
        env:
          MY_PARAM: developer
      - name: Use parameter
        if: github.ref == 'refs/heads/main'
        run: echo "This is a parameter for the main branch."
        env:
          MY_PARAM: main




