name: trial

on:
  workflow_dispatch:
    inputs:
      enable1:
        description: 'Enable workflow1'
        default: 'true'
        required: false
      enable2:
        description: 'Enable workflow2'
        default: ${{ github.event.inputs.enable1}}
        required: false

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run if workflow is enabled
        if: ${{ github.event.inputs.enable2 == 'true' }}
        run: echo ${{ github.event.inputs.enable2}}   
      - name: Run if workflow is disabled
        if: ${{ github.event.inputs.enable2 == 'false' }}
        run: echo ${{ github.event.inputs.enable2}}  
