name: trial

on:
  workflow_dispatch:
    inputs:
      enable:
        description: 'Enable workflow'
        type : boolean
        default: 'true'
        required: false

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run if workflow is enabled
        if: ${{ github.event.inputs.enable == 'true' }}
        run: echo "enabled"   
      - name: Run if workflow is disabled
        if: ${{ github.event.inputs.enable == 'false' }}
        run: echo "disabled"
