name: trial

on:
  workflow_dispatch:
    inputs:
      my-input:
        description: 'Input description'
        required: true

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: My Step
        uses: actions/setup-node@v2
        with:
          input-name: ${{ github.event.inputs.my-input }}
        run: |
          echo "Deploying to ${{ input-name }}"
