name: trial

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      my_input:
        description: 'Enter a value'
        required: true
        if: github.event.inputs.my_input != 'foo'

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: My Step
        run: echo "Hello, World!"




