name: trial


on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true
      parameter:
        description: 'Parameter name'
        required: true

jobs:
  my_job:
    strategy:
      matrix:
        branch: ${{ github.event.inputs.branch }}
        parameter: ${{ github.event.inputs.parameter }}

    runs-on: ubuntu-latest

    steps:
      - name: Step 1
        run: echo "Running ${{ matrix.branch }} branch with ${{ matrix.parameter }} parameter"

