name: trial


on:
  workflow_dispatch:
    branches:
      - main
      
    inputs:
      my_input:
      description: 'My input description'
      required: true

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print input parameter
        run: echo "My input value is ${{ inputs.my_input }}"





