name: trial

on:
  push:
    branches:
      - feature/*

jobs:
  my-job:
    runs-on: windows-latest
    steps:
      - name: My Step
        env:
          MY_PARAMETER: ${{ github.ref }}
        run: |
          echo "My parameter is $MY_PARAMETER"
