name: trial


on:
  workflow_dispatch:
    inputs:
      myCheckbox:
        description: 'My Checkbox'
        default: false
        required : true
        type : boolean
        options: [yes,no]
        disabled: true

jobs:
  myJob:
    runs-on: ubuntu-latest
    steps:
      - name: My Step
        run: echo 'Hello, world!'




