name: trial

on:
  workflow_dispatch:
    inputs:
      my_input:
        description: 'My input parameter'
        required: true
        default: ${{ github.event.inputs.my_input == 'true' }}
        
jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: My Step
        run: echo "Hello, ${{ github.event.inputs.my_input }}!"


