name: trial

on:
  workflow_dispatch:
    branches:
      - main
      - feature/*

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Do something
        run: echo "Hello ${{ inputs.name }}"
        env:
          INPUT_NAME: ${{ inputs.name }}
    inputs:
      name:
        description: 'Your name'
        required: true
