name: trial

on:
  workflow_dispatch:
    inputs:
      enable-checkbox:
        description: 'Enable checkbox'
        default: false
        required: ${{ github.event.inputs.enable-condition == 'true' }}

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Do something
        run: echo 'Hello world!'

