name: trial

on:
  workflow_dispatch:
    inputs:
      enable:
        description: 'Enable workflow'
        default: 'true'
        required: false

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run if workflow is enabled
        if: ${{ github.event.inputs.enable == 'true' }}
        run: echo ${{ github.event.inputs.enable }}
      
      - name: Run if workflow is disabled
        if: ${{ github.event.inputs.enable == 'false' }}
        run: echo ${{ github.event.inputs.enable }}
