name: trial

on:
  workflow_dispatch:
    inputs:
      enable-feature:
        description: 'Enable feature'
        required: true
      feature-name:
        description: 'Feature name'
        required: false

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Do something
        if: ${{ github.event.inputs.enable-feature == 'true' }}
        run: echo "Feature ${{ github.event.inputs.feature-name }} is enabled"



