name: trial

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Enter your name'
        required: true
      age: null


jobs:
  myJob:
    runs-on: windows-latest
    steps:
      - name: My Step
        run: echo 'Hello, world!'




