name: trial


on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: true
      tag:
        description: 'The tag to use for the deployment'
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to environment
        run: |
          echo "Deploying to ${{ github.event.inputs.environment }}"
          if [ -n "${{ github.event.inputs.tag }}" ]; then
            echo "Using tag ${{ github.event.inputs.tag }}"
          fi
