name: trial

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Your name'
        required: true
      age:
        description: 'Your age'
        required: false
        default: 'unknown'

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print input parameters
        run: |
          echo "Your name is ${{ github.event.inputs.name }}"
          echo "Your age is ${{ github.event.inputs.age }}"


