name: trial


on:
  workflow_dispatch:
    branches:
      - main
      - feature
      - test

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Do something
        run: echo "Hello, ${{ github.event.client_payload.parameter }}"

