name: trial


on:
  workflow_dispatch:
    inputs:
      param1:
        description: 'Parameter 1'
        required: true
      param2:
        description: 'Parameter 2'
        required: true
        default: ${{ github.event.inputs.param1 }}-suffix



jobs:
  myJob:
    runs-on: windows-latest
    steps:
      - name: My Step
        run: echo "Param2 Value ${{ github.event.inputs.param2 }}"




