name: trial

on:
  workflow_dispatch:
    inputs:
      my_input:
        description: 'My input parameter'
        required: true
        enable: false

jobs:
  my_job:
    runs-on: windows-latest
    steps:
      - name: Print input parameter value
        run: echo "The value of my_input is ${{ github.event.inputs.my_input }}"
